### ISSUE TITLE
[Bug]: Generate POT file GH action fails due to lack of rights to merge on main branch

### ISSUE THREAD

**Issue by asirota** [aspirepress/aspireupdate#211]
### What happened?

The Generate POT [work flow failed ](https://github.com/aspirepress/aspireupdate/actions/runs/12068273336/job/33653022020)after a recent PR merge (#209 ). Since main cannot be merged at, the workflow must be changed to support a new branch to be created first and then PRd and approved against main.

### Version

0.5 (Default)

### OS

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by afragen** [comment]
The error seems to indicate that this error happened because the branch is protected and only allows merges via PR. 

Is it possible to have more granular protections that don’t block github-bot?

Otherwise we could modify the GA to create a PR but that’s rather self defeating from automating the entire process.

**Comment by afragen** [comment]
https://github.com/orgs/community/discussions/25305

**Comment by afragen** [comment]
https://github.com/orgs/community/discussions/25305

**Comment by afragen** [comment]
This GA is what I use to keep the WP readme parser in sync. It creates a new branch and makes a PR when something has changed. It works but does require manual intervention. 

https://github.com/afragen/wordpress-plugin-readme-parser/blob/master/.github/workflows/update.yml
