### ISSUE TITLE
Multi site support

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#59]
1. Go to https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fraw.githubusercontent.com%2Faspirepress%2FAspireUpdate%2Frefs%2Fheads%2Fplayground-ready%2Fassets%2Fplayground%2Fblueprint.json
2. Go to settings and creste a  multi site Network

3. Go to Network admin dashboard 

/wp-admin/network/update-core.php has updates but no AP.

/wp-admin/index.php?page=aspireupdate-settings has AP but no updates

Expected that the AP menu would be in multi site Network instead.

**Comment by asirota** [comment]
Can you please add some screen shots on what you are describing?

**Comment by ipajen** [comment]
![IMG_8500](https://github.com/user-attachments/assets/bbaa7f33-0e35-422d-965d-c4e8dcfd8a30)
![IMG_8501](https://github.com/user-attachments/assets/553ff1d3-a9cf-415c-8fac-40741ecbddb1)
![IMG_8502](https://github.com/user-attachments/assets/cc8f5517-61b8-4cf1-88af-d3fffdb01d6f)

**Comment by asirota** [comment]
I see. The AU settings doesn't appear under multisite. Glad you are using playgrounds to test. It saves tons of time.

**Comment by namithj** [comment]
This one is a bit tricky.

There are two ways to do this

1) Show the AspireUpdate settings on each site under a multisite. - Which is easy to implement but its pretty much useless as updates are usually handled by network-admin

2) Create a new settings page just for multisite under network admin saving the options to network-settings instead of individual site options and make it apply to all sub sites.  This will be the proper way to handle it but will take more work to get it done and we will have to test everything on both places once this is done.

Need to decide whether we want to take this up for V1

**Comment by asirota** [comment]
I would say kick this to a subsequent Phase of the project post the launch.  I cannot tell how many websites use multisite but the biggest one is WordPress.com.

**Comment by ipajen** [comment]
Some stats 
https://trends.builtwith.com/widgets/WordPress-Multisite

If not included in phase1 it would be great to add info on docs about it.

**Comment by asirota** [comment]
About 2M out of 400+M sites use Multisite. I think if there is a particularly important site that wants to use AspirePress we would jump on this, but not quite yet.

**Comment by namithj** [comment]
I think those sites can still use the wp-config.php way to configure the plugin.

Need to test and verify.

**Comment by afragen** [comment]
I have a PR. It assumes that AspireUpdate should be network activated on multisite.
