### ISSUE TITLE
License mismatch 

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#68]
Readme.md GPLv2
Readme.txt GPL-3.0-or-later
aspire-update.php GPL-3.0-or-later

On https://aspirepress.org/about-us/ it says GPL v2

Possibly versions:

GPL-3.0-or-later
GPL-3.0-only
GPL-2.0-or-later
GPL-2.0-only

I am uncertain what license we have but it’s should be the same on all places

**Comment by yosefeliezrie** [comment]
The GNU General Public License (GPL) is one of the most widely used free software licenses. Here are the key differences between GPL version 2.0 (GPLv2) and GPL version 3.0 (GPLv3):

### 1. **Patent Retaliation**
   - **GPLv2**: Does not explicitly address patents. 
   - **GPLv3**: Includes provisions to counteract patent aggression. If a patent litigation is initiated against a user for using the software, the license for that user can be revoked unless the litigation is withdrawn.

### 2. **Tivoization**
   - **GPLv2**: Does not address the issue of "Tivoization," where software is distributed in devices that require special keys or authorization to modify the software on the device.
   - **GPLv3**: Specifically tackles Tivoization by ensuring that users can modify the software on the device if they can install modified versions on their own copies of the software.

### 3. **Digital Rights Management (DRM)**
   - **GPLv2**: Does not explicitly deal with DRM.
   - **GPLv3**: Prohibits the use of DRM that would prevent users from exercising rights granted by the GPL. If an effective technological measure is used to control distribution or modification, the licensor must provide the means to remove this measure.

### 4. **Compatibility**
   - **GPLv2**: Is designed to be compatible with other licenses like the LGPL, but its strict "or any later version" clause means that if this clause is removed or changed, linking with GPLv2 code might not be straightforward.
   - **GPLv3**: Offers more flexibility for compatibility with other open source licenses by allowing for "GPLv3 or later" or "GPLv3 only" options, making it easier to combine GPLv3 software with other GPL-compatible licenses.

### 5. **Geographical Restrictions**
   - **GPLv2**: Does not address geographical restrictions on software distribution or use.
   - **GPLv3**: Bans any geo-restrictions on the exercise of rights granted by the license, which was particularly relevant in light of U.S. export regulations on cryptography at the time of GPLv3's drafting.

### 6. **License Termination**
   - **GPLv2**: Termination of the license for a violation can be permanent unless the copyright holder explicitly reinstates the license.
   - **GPLv3**: Provides an automatic reinstatement of the license if the violation is corrected within 30 days of being notified.

### 7. **Installer Requirements**
   - **GPLv3** adds an obligation for interactive user interfaces to prominently offer users an opportunity to view the license and disclaimer of warranty.

### 8. **Additional Permissions**
   - **GPLv3** introduces the concept of "Additional Permissions" where copyright holders can allow certain actions that would otherwise violate the GPL without altering the core GPL conditions for everyone else.

These changes reflect evolving concerns in software freedom, legal landscapes, and the practicalities of software distribution and use. The choice between GPLv2 and GPLv3 often depends on the project's goals regarding software freedom, compatibility with other licenses, and protection against proprietary practices.

**Comment by ipajen** [comment]
@yosefeliezrie  Just to confirm you want the PR to be: GPLv2
(not GPL-2.0-or-later or GPL-2.0-only)

**Comment by asirota** [comment]
whatever we decided we should add LICENSE.md with the full license contents into the repo at the root level of the plugin. This should be added to all our prokects to be sure.

**Comment by yosefeliezrie** [comment]
Yes, confirming GPL2 for all WordPress plug-ins and themes

**Comment by namithj** [comment]
Whats the status on this one?  Can this be closed?

**Comment by ipajen** [comment]
Issue still exist and a LICENSE.md  needs to created.

**Comment by yosefeliezrie** [comment]
@ipajen 

Are you able to please create a pull request to update this and reference this issue

Thanks so much.

**Comment by ipajen** [comment]
@yosefeliezrie Sorry I think its better someone else does it as it should include a LICENSE.md and I will stay with QA ;) Thanks

**Comment by yosefeliezrie** [comment]
> @yosefeliezrie Sorry I think its better someone else does it as it should include a LICENSE.md and I will stay with QA ;) Thanks

Okay, no problem. Thanks for reporting, will get this updated.

**Comment by asirota** [comment]
Yes absolutely.

**Comment by namithj** [comment]
This can be closed, Right?

**Comment by ipajen** [comment]
Closing as it’s updated  with same license type now.
